#ifndef AARCH64_MEM_IDX_H_
#define AARCH64_MEM_IDX_H_

#define MEM_NORMAL_IDX 0
#define MEM_DEV_STRICT_IDX 1
#define MEM_DEV_RELAXED_IDX 2
#define MEM_NON_CACHEABLE_IDX 3

#define MEM_ATTR_NORMAL 0xff
#define MEM_ATTR_DEV_STRICT 0x00
#define MEM_ATTR_DEV_RELAXED 0x0c
#define MEM_ATTR_NON_CACHEABLE 0x44

#endif
